version: 1.0.{build}-{branch}

cache:
  - node_modules

environment:
  matrix:
    - NOV: 7
    - NOV: 6
    - NOV: 5
    - NOV: 4
    - NOV: 3
    - NOV: 2
    - NOV: 1
    - NOV: 0

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NOV $env:PLATFORM
  - npm install

build: off

before_test:
  - node -v
  - npm -v

test_script:
  - npm test
  - npm test --win

after_test:
  - npm pack
  - cd rails
  - rake build
  - mv pkg/* ..

artifacts:
  - path: "*.tgz"
    name: NPM package
  - path: "*.gem"
    name: Ruby gem

